apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  labels:
    app: voting-app
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
      labels:
        name: vote
        app: voting-app
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}
        env:
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.azurestorageaccountsecret }}
              key: account-name
        - name: AZURE_STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.azurestorageaccountsecret }}
              key: access-key
        ports:
        - containerPort: {{ .Values.port }}
        - containerPort: 8000
