apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: voting-app
spec:
  selector:
    app: voting-app
  type: LoadBalancer
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: vote
