# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - vote/*
    - .azure-pipelines/vote-cicd.yaml
    - manifests/vote.yaml

resources:
- repo: self

variables:
- group: VoterAppSecrets  
  # Container registry service connection established during pipeline creation
- name: dockerRegistryServiceConnection 
  value: '621a834f-49c3-4f4e-a151-fa59b0924954'
- name: imageRepository 
  value: 'geverghevotingappkubernetes'
- name: containerRegistry 
  value: 'forresterdemo.azurecr.io'
- name: dockerfilePath 
  value: 'vote/Dockerfile'
- name: tag 
  value: '$(Build.BuildId)'
- name: imagePullSecret 
  value: 'forresterdemosecret'
- name: azure-storage-secret 
  value: 'azure-storage'
 

  # Agent VM image name
- name: vmImageName 
  value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: vote/helm
      artifact: vote/helm

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Development.contoso-dev-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: "contoso-dev-aks"
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Create storage secret
            inputs: 
              action: createSecret
              secretType: generic
              secretName: $(azure-storage-secret )
              secretArguments: --from-literal=azure-storage-account-name=$(azure-storage-username) --from-literal=azure-storage-account-key=$(azure-storage-key)
              kubernetesServiceConnection: 'Development-contoso-dev-aks-1582199981119'
              namespace: "contoso-dev-aks"

          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/vote/helm

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: "contoso-dev-aks"
              manifests: $(bake.manifestsBundle)
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

