# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Infra
  displayName: Create/Update Infra
  jobs:    
  - job: deployVM

    displayName: Create Or Update ForresterDemoCluster    
    steps:    
    - task: AzureKeyVault@1
      displayName: Fetch Storage Secrets from Azure Key vault
      inputs:
        azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
        KeyVaultName: 'ForresterDemoKeyVault'
        SecretsFilter: '*'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
        subscriptionId: 'afc11291-9826-46be-b852-70349146ddf8'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ForresterDemo'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/arm-templates/aks.json'
        overrideParameters: |
          -dnsPrefix "forresterdemocluster-dns" -adminUsername "MC_ForresterDemoCluster_ForresterDemo_EastUS" -sshRSAPublicKey "$(aks-arm-sshrsa-new)" -servicePrincipalClientId "$(aks-arm-sp-client-id)" -servicePrincipalClientSecret "$(aks-arm-sp-client-password)"
        deploymentMode: 'Incremental'