# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - worker/*
    - .azure-pipelines/worker-cicd.yaml
    - manifests/worker.yaml

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '621a834f-49c3-4f4e-a151-fa59b0924954'
  imageRepository: 'gevergheworkerappkubernetes'
  containerRegistry: 'forresterdemo.azurecr.io'
  dockerfilePath: 'worker/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'forresterdemosecret'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - template: buildJob.yml@templates
    parameters:
      name: 'worker'
      vmImageName: $(vmImageName)
      imageRepository: $(imageRepository)
      dockerfilePath: $(dockerfilePath)
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
      tag: $(tag)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Stage.contoso-stage-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              namespace: contoso-stage-aks
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - task: KubernetesManifest@0
            name: bake
            displayName: Bake K8s manifests from Helm chart
            inputs:
              action: bake
              renderType: helm2
              helmChart: $(Pipeline.Workspace)/worker/helm
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(bake.manifestsBundle)
              namespace: contoso-stage-aks
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

